"""user_profile_history user+recorded composite index

Revision ID: b78b256c2b20
Revises: c849579de6c4
Create Date: 2026-06-17 16:16:36.426789

"""
from typing import Sequence, Union

from alembic import op

# 본 마이그레이션은 인덱스 DDL(op.*)만 사용 → autogen 템플릿의 `import sqlalchemy as sa`
# 는 미사용이라 제거(F401). 컬럼 추가 마이그레이션은 sa 를 쓰므로 그대로 둔다.


# revision identifiers, used by Alembic.
revision: str = 'b78b256c2b20'
down_revision: Union[str, None] = 'c849579de6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_history_user_id'), table_name='user_profile_history')
    op.create_index('ix_history_user_recorded', 'user_profile_history', ['user_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_history_user_recorded', table_name='user_profile_history')
    op.create_index(op.f('ix_user_profile_history_user_id'), 'user_profile_history', ['user_id'], unique=False)
    # ### end Alembic commands ###
